#!/bin/bash
#SBATCH -N 1
#SBATCH -p GPU
#SBATCH --ntasks-per-node 1
#SBATCH -t 26:00:00
#SBATCH --gres=gpu:p100:2

#echo commands to stdout
set -x

#move to working directory
# this job assumes:
# - all input data is stored in this directory 
# - all output should be stored in this directory 

#run GPU program
conda activate /pylon5/ir5fq3p/likhache/aditya/dope_env
cd /pylon5/ir5fq3p/likhache/aditya/Deep_Object_Pose
which python
export PYTHONPATH=$PYTHONPATH:/pylon5/ir5fq3p/likhache/aditya/Deep_Object_Pose
source runme_gpu |& tee log
